type Query {
  accessToken: String!
}

type Mutation {
  setAccessToken(accessToken: String!): String!
}

query getAccessToken {
  accessToken @client
}

mutation setAccessToken($accessToken: String!) {
  setAccessToken(accessToken: $accessToken) @client
}
